temas = {
    "brands": [
        "apple", "microsoft", "google", "samsung", "amazon", "intel", "hp", "dell", "sony",
        "facebook", "instagram", "twitter", "linkedin", "youtube", "whatsapp",
        "mercedes", "bmw", "toyota", "volkswagen", "honda", "ferrari", "porsche",
        "nike", "adidas", "puma", "converse", "vans", "ray-ban", "levi's",
        "coca-cola", "pepsi", "fanta", "mcdonalds", "starbucks", "nestlé",
        "netflix", "disney", "spotify", "playstation", "xbox", "nintendo",
        "lg", "huawei", "canon", "philips", "casio", "asus", "lenovo",
        "visa", "mastercard", "paypal", "uber", "airbnb", "booking",
        "rolex", "gucci", "colgate", "gillette"
    ],

    "feelings": [
        "alegria", "amor", "felicidade", "esperança", "gratidão",
        "carinho", "confiança", "entusiasmo", "orgulho", "compaixão",
        "tristeza", "raiva", "medo", "ansiedade", "frustração",
        "angústia", "decepção", "ciúme", "desespero", "solidão",
        "saudade", "surpresa", "nostalgia", "admiração", "serenidade", 
        "otimismo", "coragem", "insegurança", "vergonha", "alívio",
        "euforia", "paixão", "pânico", "fúria", "tormento",
        "contentamento", "ternura", "curiosidade", "realização", "paz"
    ],

    "elements": [ 
        "Hidrogênio", "Lítio", "Sódio", "Potássio", "Rubídio", "Césio", "Frâncio",
        "Berílio", "Magnésio", "Cálcio", "Estrôncio", "Bário", "Rádio",
        "Escândio", "Titânio", "Vanádio", "Cromo", "Manganês", "Ferro", "Cobalto", "Níquel", 
        "Cobre", "Zinco", "Ítrio", "Zircônio", "Nióbio", "Molibdênio", "Tecnécio", "Rutênio", 
        "Ródio", "Paládio", "Prata", "Cádmio", "Háfnio", "Tântalo", "Tungstênio", "Rênio", 
        "Ósmio", "Irídio", "Platina", "Ouro", "Mercúrio", "Rutherfordio", "Dúbnio", 
        "Seabórgio", "Bóhrio", "Hássio", "Meitnério", "Darmstádtio", "Roentgênio", "Copernício",
        "Alumínio", "Gálio", "Índio", "Tálio", "Estanho", "Chumbo", "Bismuto", "Antímônio",
        "Lantânio", "Cério", "Praseodímio", "Neodímio", "Promécio", "Samário", "Európio", 
        "Gadolínio", "Térbio", "Disprósio", "Hólmio", "Érbio", "Túlio", "Itérbio", "Lutécio",
        "Actínio", "Tório", "Protactínio", "Urânio", "Netúnio", "Plutônio", "Amerício", 
        "Cúrio", "Berkélio", "Califórnio", "Einstênio", "Férmio", "Mendelévio", "Nobélio", 
        "Laurêncio", "Boro", "Silício", "Germânio", "Arsênio", "Telúrio", "Polônio",
        "Carbono", "Nitrogênio", "Oxigênio", "Fósforo", "Enxofre", "Selênio",
        "Flúor", "Cloro", "Bromo", "Iodo", "Astato", "Tenessino",
        "Hélio", "Neônio", "Argônio", "Criptônio", "Xenônio", "Radônio", "Oganesson"
    ],

    "musical_instruments": [
        "violão", "piano", "bateria", "flauta", "guitarra",
        "violino", "baixo", "trompete", "teclado", "harpa",
        "violoncelo", "clarinete", "fagote", "oboé", "viola",
        "gaita", "cavaquinho", "cítara", "marimba", "pandeiro",
        "tamborim", "zabumba", "triângulo", "caixa", "timba",
        "pratos", "tuba", "tambor", "maracas", "berimbau",
        "ocarina", "banjo", "clarineta", "xilofone", "flauta doce",
        "acordeão", "gaita de fole", "dulcimer", "bandolim", "ukulele",
        "saxofone", "didgeridoo", "flauta pan", "teremim", "kalimba",
        "lira", "gongo", "cazoo", "flautim", "bongô"
    ],

    'nature': [
        "árvore", "floresta", "montanha", "cachoeira", "oceano",
        "deserto", "planície", "vale", "rio", "lago",
        "vulcão", "pedra", "areia", "vento", "chuva",
        "neve", "granizo", "relâmpago", "tempestade", "nuvem",
        "céu", "estrela", "lua", "sol", "campo",
        "jardim", "grama", "folha", "flor", "arbusto",
        "fauna", "flora", "trilha", "penhasco", "coral",
        "praia", "ilha", "pantanal", "manguezal", "selva",
        "bosque", "árido", "savanas", "geada", "gelo",
        "caverna", "abismo", "pântano", "nascer do sol", "pôr do sol",
        "galho"
    ],

    'sports': [
        "futebol", "basquete", "vôlei", "tênis", "natação",
        "atletismo", "ciclismo", "boxe", "karatê", "judô",
        "esgrima", "ginástica", "handebol", "rugby", "críquete",
        "hóquei", "golfe", "escalada", "patinação", "surfe",
        "remo", "canoagem", "skate", "snowboard", "alpinismo",
        "triatlo", "arco e flecha", "badminton", "beisebol", "futsal",
        "polo aquático", "kitesurf", "motocross", "corrida", "salto em altura",
        "salto com vara", "caminhada", "maratona", "levantamento de peso", "luta livre",
        "pingue-pongue", "peteca", "boliche", "dardos", "bilhar",
        "esqui", "taekwondo", "kickboxing", "windsurf", "parapente",
        "corrida de cavalo"
    ],
    "objects": [
        "mesa", "cadeira", "sofá", "cama", "almofada",
        "computador", "teclado", "mouse", "monitor", "telefone",
        "celular", "televisão", "geladeira", "fogão", "micro-ondas",
        "liquidificador", "ventilador", "luminária", "abajur", "relógio",
        "espelho", "prateleira", "livro", "caneta", "lápis",
        "borracha", "caderno", "mochila", "bolsa", "carteira",
        "óculos", "guarda-chuva", "copo", "garrafa", "prato",
        "talher", "colher", "garfo", "faca", "panela",
        "travesseiro", "tapete", "pente", "escova", "chuveiro",
        "torradeira", "ferro de passar", "secador", "caixa", "gaveta",
        "armário", "sapato", "vassoura", "balde", "escada",
        "bateria", "controle remoto", "chave", "cadeado", "cesto"
    ],
    "animals": [
        "cachorro", "gato", "elefante", "leão", "tigre",
        "urso", "girafa", "zebra", "hipopótamo", "rinoceronte",
        "macaco", "pássaro", "peixe", "tartaruga", "coelho",
        "cavalo", "boi", "ovelha", "cabra", "porco",
        "galo", "galinha", "patinho", "peru", "pavão",
        "esquilo", "raposa", "lobo", "urso polar", "pantera",
        "onça", "puma", "jacaré", "cobra", "lagarto",
        "crocodilo", "aranha", "formiga", "abelha", "mosca",
        "borboleta", "cervo", "antílope", "camelo", "búfalo",
        "kanguru", "pingüim", "pinguim", "foca", "golfinho",
        "baleia", "tubarão", "morcego", "estrela-do-mar", "vaca",
        "mupe", "cavalo-marinho", "caranguejo", "molusco", "marisco"
    ],
    "colors": [
        "vermelho", "azul", "verde", "amarelo", "laranja",
        "roxo", "rosa", "branco", "preto", "cinza",
        "marrom", "bege", "violeta", "indigo", "turquesa",
        "chartreuse", "salmon", "púrpura", "ciano", "magenta",
        "esmeralda", "açafrão", "ouro", "prata", "bronze",
        "coral", "escarlet", "caramelo", "teal", "lavanda",
        "branco-neve", "azul-marinho", "azul-claro", "verde-musgo", "verde-menta",
        "verde-lima", "amarelo-claro", "amarelo-ouro", "amarelo-pálido", "azul-turquesa",
        "azul-escuro", "turquesa-escuro", "verde-floresta", "roxo-claro", "laranja-claro",
        "verde-água", "rosa-pastel", "laranja-vivo", "roxo-escuro", "verde-oliva",
        "azul-petróleo", "bege-escuro", "azul-cobalto", "cinza-claro", "cinza-escuro",
        "pêssego", "rosa-choque", "vermelho-vivo", "berinjela", "marron-claro"
    ],
    "countries": [
        "Brasil", "Estados Unidos", "Argentina", "França", "Itália",
        "Alemanha", "Japão", "China", "Rússia", "México",
        "Canadá", "Reino Unido", "Índia", "Austrália", "África do Sul",
        "Espanha", "Portugal", "Colômbia", "Polônia", "Egito",
        "Coreia do Sul", "Suécia", "Suíça", "Países Baixos", "Noruega",
        "Turquia", "Coreia do Norte", "Irã", "Arábia Saudita", "Israel",
        "Grécia", "Turquia", "Tailândia", "Indonésia", "Vietnã",
        "Nova Zelândia", "Paquistão", "Bangladesh", "Filipinas", "Irlanda",
        "República Tcheca", "Hungria", "Áustria", "Finlândia", "Dinamarca",
        "Noruega", "Bélgica", "Romênia", "Polônia", "Ucrânia",
        "Iraque", "Síria", "Afeganistão", "Líbano", "Quênia",
        "Cuba", "Peru", "Chile", "Venezuela", "Bulgária"
    ],
    "games": [
        "Minecraft", "The Sims", "Fortnite", "League of Legends", "World of Warcraft",
        "Counter-Strike: Global Offensive", "Valorant", "Among Us", "Roblox", "Cyberpunk",
        "The Witcher", "Red Dead Redemption", "Call of Duty: Warzone", "Grand Theft Auto", "Apex Legends",
        "Hearthstone", "PUBG", "Rocket League", "Fall Guys", "Overwatch",
        "Stardew Valley", "Terraria", "Factorio", "Civilization", "Dark Souls",
        "The Elder Scrolls", "Genshin Impact", "Dota", "Rainbow Six Siege", "FIFA",
        "NBA 2K", "Far Cry", "No Man's Sky", "Dead by Daylight", "Subnautica",
        "Watch Dogs", "Battlefield", "Diablo", "Path of Exile", "Escape from Tarkov",
        "Total War: Warhammer", "Tomb Raider", "The Forest", "Dead Space",
        "Minecraft Dungeons", "Unravel", "Assassin's Creed", "Nier: Automata", "Control",
        "Destiny", "Spelunky", "Super Meat Boy", "Cuphead", "Darkest Dungeon",
        "Outer Worlds", "Hollow Knight", "Fallout", "Borderlands", "The Division"
    ],
    "movies": [
        "O Poderoso Chefão", "O Senhor dos Anéis", "Harry Potter", "Star Wars", "Titanic",
        "Vingadores", "Jurassic Park", "Matrix", "O Rei Leão", "Gladiador",
        "Inception", "Interestelar", "A Origem", "O Exorcista", "Clube da Luta",
        "Forrest Gump", "O Silêncio dos Inocentes", "Pulp Fiction", "Cidadão Kane", "O Grande Lebowski",
        "O Exterminador do Futuro", "Avatar", "Vingadores: Ultimato", "O Hobbit", "O Diabo Veste Prada",
        "O Lobo de Wall Street", "Os Incríveis", "Shrek", "Piratas do Caribe", "O Cavaleiro das Trevas",
        "A Viagem de Chihiro", "Jurassic World", "Mad Max: Estrada da Fúria", "Django Livre", "Frozen",
        "A Bela e a Fera", "Rei Arthur", "O Pianista", "O Labirinto do Fauno", "Mulher Maravilha",
        "A Lista de Schindler", "O Grande Hotel Budapeste", "Doutor Estranho", "O Jogo da Imitação", "Coringa",
        "Os Suspeitos", "O Menino do Pijama Listrado", "O Show de Truman", "À Procura da Felicidade", "As Branquelas",
        "La La Land", "Jurassic Park: O Parque dos Dinossauros", "O Profissional"
    ],
    "series": [
        "Game of Thrones", "Breaking Bad", "Stranger Things", "Friends", "The Office",
        "The Crown", "The Mandalorian", "The Witcher", "Sherlock", "Black Mirror",
        "Money Heist", "Narcos", "Peaky Blinders", "The Walking Dead", "The Sopranos",
        "Westworld", "House of Cards", "True Detective", "Fargo", "Better Call Saul",
        "The Boys", "The Haunting of Hill House", "Rick and Morty", "Dark", "Prison Break",
        "The Flash", "Arrow", "Daredevil", "The Umbrella Academy", "How I Met Your Mother",
        "The Big Bang Theory", "Friends", "Mindhunter", "Vikings", "The Expanse",
        "Supernatural", "Doctor Who", "Hannibal", "Narcos: Mexico", "The Last Dance",
        "Sex Education", "The Queen's Gambit", "The Handmaid's Tale", "The Good Place", "Orange is the New Black",
        "Chernobyl", "The Marvelous Mrs. Maisel", "Lucifer", "Fleabag", "GLOW",
        "The 100", "The Boys", "Black Sails", "The Punisher", "Loki", "Better Call Saul",
        "Peaky Blinders", "Big Mouth", "Ted Lasso", "Narcos", "The Outsider"
    ],
    "fruits": [
        "maçã", "banana", "laranja", "uva", "abacaxi",
        "manga", "morango", "kiwi", "limão", "melancia",
        "melão", "pera", "pêssego", "cereja", "ameixa",
        "abacate", "framboesa", "amora", "maracujá", "pitanga",
        "carambola", "graviola", "acerola", "mamão", "tangerina",
        "caju", "jabuticaba", "figo", "romã", "coco",
        "açaí", "caqui", "nectarina", "goiaba", "jaca",
        "pinha", "lichia", "cupuaçu", "seriguela", "physalis",
        "sapoti", "kumquat", "araticum", "bacuri", "buriti",
        "umbu", "tamarindo", "pitaya", "longan", "rambutã"
    ],
    "professions": [
        "médico", "advogado", "engenheiro", "professor", "arquiteto",
        "programador", "contador", "designer", "enfermeiro", "veterinário",
        "farmacêutico", "psicólogo", "jornalista", "policial", "bombeiro",
        "motorista", "piloto", "chefe de cozinha", "garçom", "eletricista",
        "pintor", "carpinteiro", "mecânico", "pedreiro", "soldador",
        "barbeiro", "esteticista", "fotógrafo", "cinegrafista", "ator",
        "atriz", "escritor", "editor", "publicitário", "bibliotecário",
        "cientista", "astrônomo", "químico", "biólogo", "físico",
        "historiador", "geógrafo", "economista", "analista de sistemas", "técnico em informática",
        "tradutor", "marceneiro", "ourives", "florista", "dublador"
    ],
    "foods": [
        "pizza", "hambúrguer", "lasanha", "sushi", "tacos",
        "burrito", "risoto", "nhoque", "macarrão", "falafel",
        "shawarma", "paella", "curry", "ramen", "tempura",
        "ceviche", "quiche", "croissant", "baguete", "pão sírio",
        "churrasco", "frango assado", "bife à milanesa", "fish and chips", "salada caesar",
        "gnocchi", "carbonara", "esfiha", "dumpling", "moqueca",
        "guacamole", "pad thai", "arroz frito", "kebab", "satay",
        "waffles", "panqueca", "crepe", "gelato", "brigadeiro",
        "brownie", "mousse de chocolate", "cheesecake", "pudim", "sopa de cebola",
        "torta de maçã", "bolo de cenoura", "donuts", "churros", "tiramisu"
    ]
    
}


