temas = {
    'animals': [
        "cachorro", "gato", "elefante", "tigre", "leão",
        "girafa", "rinoceronte", "zebra", "macaco", "cobra",
        "cavalo", "urso", "pato", "pinguim", "urso polar",
        "coelho", "raposa", "jacaré", "lobo", "gato selvagem",
        "pantera", "onça", "baleia", "golfinho", "lince",
        "capivara", "preguiça", "pinguim imperador", "arara", "gaivota",
        "corvo", "rato", "morcego", "galo", "papagaio",
        "camelo", "canguru", "tamanduá", "sagui", "dragão",
        "águia", "tucano", "hipopótamo", "guepardo", "antílope",
        "borboleta", "formiga", "abelha", "esquilo", "castor",
        "polvo", "hamster", "panda", "coala", "gorila",
        "ouriço", "guaxinim", "avestruz", "flamingo", "pavão",
        "tartaruga", "crocodilo", "tubarão", "cavalo-marinho", "água-viva"
    ],
    'fruits': [
        "banana", "maçã", "uva", "laranja", "abacaxi",
        "morango", "kiwi", "manga", "cereja", "melancia",
        "pêssego", "pera", "ameixa", "maracujá", "amora",
        "figo", "pitanga", "mamão", "caqui", "jabuticaba",
        "acerola", "carambola", "lichia", "groselha", "tamarindo",
        "jambo", "graviola", "abiu", "cupuaçu", "bacaba",
        "goiaba", "romã", "tangerina", "framboesa", "mirtilo",
        "coco", "jaca", "sapoti", "cajá", "ameixa brasileira",
        "pitaya", "damasco", "nectarina", "toranja", "limão",
        "amora", "tâmara", "marmelo", "sabugueiro", "oxicoco",
        "amora-silvestre", "groselha-espinhosa", "kumquat", "durião", "melão"
    ],
    'countries': [
        "brasil", "argentina", "canadá", "nova zelândia", "japão",
        "alemanha", "frança", "itália", "rússia", "méxico",
        "espanha", "reino unido", "estados unidos", "china", "índia",
        "áfrica do sul", "colômbia", "suíça", "portugal", "holanda",
        "islândia", "noruega", "bielorrússia", "peru", "iraque",
        "polônia", "singapura", "marrocos", "egito", "tailândia",
        "dinamarca", "finlândia", "grécia", "turquia", "bélgica",
        "suécia", "áustria", "hungria", "romênia", "ucrânia",
        "irlanda", "croácia", "bulgária", "letônia", "estônia",
        "lituânia", "eslováquia", "eslovênia", "luxemburgo", "chipre",
        "malta", "nepal", "vietnã", "malásia", "indonésia"
    ],
    'colors': [
        "vermelho", "azul", "verde", "amarelo", "preto",
        "branco", "roxo", "rosa", "cinza", "laranja",
        "bege", "turquesa", "violeta", "dourado", "cobre",
        "bronze", "magenta", "coral", "pistache", "lima",
        "pinho", "lavanda", "chartreuse", "verde musgo", "amarelo canário",
        "cerúleo", "pérola", "carmim", "índigo", "azul profundo",
        "salmão", "berinjela", "vinho", "caramelo", "terracota",
        "marrom", "azul marinho", "azul-petróleo", "verde-oliva", "carmesim",
        "bordô", "malva", "bege escuro", "cáqui", "castanho",
        "azul-celeste", "siena", "escarlate", "marfim", "platina"
    ],
    'professions': [
        "médico", "professor", "engenheiro", "juiz", "policial",
        "bombeiro", "padeiro", "eletricista", "motorista", "carpinteiro",
        "arquiteto", "dentista", "enfermeiro", "designer", "psicólogo",
        "jornalista", "programador", "cientista", "fotógrafo", "cabeleireiro",
        "pedreiro", "veterinário", "gerente", "cozinheiro", "pedagogo",
        "funcionário público", "economista", "contador", "secretário", "segurança",
        "piloto", "mecânico", "técnico de TI", "analista", "fisioterapeuta",
        "advogado", "nutricionista", "farmacêutico", "atleta", "músico",
        "arqueólogo", "astrônomo", "biólogo", "químico", "detetive",
        "diplomata", "historiador", "bibliotecário", "optometrista", "paramédico",
        "pesquisador", "sociólogo", "tradutor", "escritor", "zoólogo"
    ],
    'objects': [
        "cadeira", "mesa", "computador", "telefone", "livro",
        "lâmpada", "televisão", "copo", "caneta", "relógio",
        "bicicleta", "sofá", "travesseiro", "janela", "porta",
        "guarda-chuva", "fone de ouvido", "abajur", "escova",
        "controle remoto", "micro-ondas", "panela", "escada", "banquinho",
        "carteira", "chave", "cofre", "radar", "joia",
        "banco", "espelho", "pintura", "vaso", "mala",
        "impressora", "calculadora", "calendário", "tesoura", "caderno",
        "grampeador", "régua", "bússola", "envelope", "clipe",
        "mochila", "carregador", "teclado", "mouse", "monitor",
        "câmera", "torradeira", "liquidificador", "chaleira", "telescópio"
    ],
    'sports': [
        "futebol", "basquete", "vôlei", "natação", "tênis",
        "ciclismo", "atletismo", "golfe", "surfe", "skate",
        "handebol", "hóquei", "rúgbi", "boxe", "jiu-jítsu",
        "luta livre", "esgrima", "tiro ao alvo", "caratê", "judô",
        "polo aquático", "patinação", "escalada", "bungee jumping", "capoeira",
        "lanchas", "vela", "futebol americano", "wrestling", "softbol",
        "trampolim", "tênis de mesa", "esconde-esconde", "vôlei", "beisebol",
        "tiro com arco", "badminton", "críquete", "mergulho", "ginástica",
        "lacrosse", "remo", "squash", "triatlo", "windsurf",
        "polo", "curling", "parkour", "snowboard", "levantamento de peso"
    ],
    "foods": [
        "pizza", "hambúrguer", "lasanha", "salada", "sushi",
        "churrasco", "batata", "arroz", "feijão", "bolo",
        "pão", "torta", "mousse", "bife", "frango",
        "sopa", "macarrão", "chocolate", "cereal", "panqueca",
        "curau", "omelete", "pastel", "crepe", "batata frita",
        "salada de frutas", "bolacha", "empada", "pé de moleque", "tacacá",
        "feijão tropeiro", "feijoada", "tabule", "salada de batata", "brigadeiro",
        "gelatina", "biscoito", "cocada", "rocambole", "bolo de milho",
        "muffin", "croissant", "waffle", "sanduíche", "burrito",
        "taco", "nachos", "risoto", "paella", "curry",
        "sashimi", "tempurá", "dim sum", "lámen", "pho"
    ],
    "musical_instruments": [
        "violão", "piano", "bateria", "flauta", "guitarra",
        "violino", "baixo", "trompete", "teclado", "harpa",
        "violoncelo", "clarinete", "fagote", "oboé", "viola",
        "gaita", "cavaquinho", "cítara", "marimba", "pandeiro",
        "tamborim", "zabumba", "triângulo", "caixa", "timba",
        "pratos", "tuba", "tambor", "maracas", "berimbau",
        "ocarina", "banjo", "clarineta", "xilofone", "flauta doce",
        "acordeão", "gaita de fole", "dulcimer", "bandolim", "ukulele",
        "saxofone", "didgeridoo", "flauta pan", "teremim", "kalimba",
        "lira", "gongo", "cazoo", "flautim", "bongô"
    ],
    "movies_and_series": [
        "titanic", "matrix", "guerra nas estrelas", "senhor dos anéis", "harry potter",
        "breaking bad", "game of thrones", "friends", "the office", "stranger things",
        "vingadores", "batman", "jurassic park", "indiana jones", "o poderoso chefão",
        "pulp fiction", "forrest gump", "la casa de papel", "black mirror", "dark",
        "lost", "prison break", "supernatural", "the crown", "westworld",
        "how i met your mother", "better call saul", "dexter", "orange is the new black", "house",
        "greys anatomy", "the walking dead", "mad men", "true detective", "chernobyl",
        "a origem", "interestelar", "um sonho de liberdade", "clube da luta", "the witcher",
        "round 6", "bridgerton", "wandavision", "mandalorian", "succession",
        "wandinha", "ozark", "peaky blinders", "sherlock", "narcos"
    ],
    "games": [
        "minecraft", "mario bros", "zelda", "tetris", "pac-man",
        "god of war", "grand theft auto", "fifa", "the sims", "portal",
        "counter strike", "league of legends", "world of warcraft", "pokemon", "sonic",
        "resident evil", "mortal kombat", "final fantasy", "call of duty", "assassins creed",
        "metal gear solid", "red dead redemption", "super smash bros", "overwatch", "valorant",
        "fortnite", "among us", "stardew valley", "undertale", "cuphead",
        "dark souls", "hollow knight", "civilization", "the witcher", "hades",
        "elden ring", "cyberpunk", "dead cells", "fallout", "skyrim",
        "bioshock", "mass effect", "doom", "half-life", "portal",
        "terraria", "borderlands", "dead space", "diablo", "genshin impact"
    ],
    "brands": [
        "nike", "adidas", "puma", "coca-cola", "pepsi", "fanta", 
        "samsung", "apple", "xiaomi", "microsoft", "google", "amazon",
        "netflix", "disney", "spotify", "mercedes", "bmw", "audi",
        "honda", "toyota", "volkswagen", "vans", "converse", "zara",
        "gucci", "prada", "rolex", "facebook", "instagram", "twitter",
        "linkedin", "playstation", "xbox", "nintendo", "colgate", 
        "gillette", "nestlé", "mcdonalds", "burger king", "starbucks", 
        "dell", "hp", "intel", "canon", "sony", "philips", "lg", "asus", 
        "lenovo", "huawei", "fila", "reebok", "oakley", "rayban",
        "lacoste", "levis", "timberland", "havaianas", "olympikus",
        "mizuno", "asics", "ferrari", "lamborghini", "porsche",
        "chevrolet", "hyundai", "nivea", "avon", "natura", "boticário",
        "apple", "motorola", "casio", "yamaha", "swift", "mastercard",
        "visa", "paypal", "fedex", "walmart", "carrefour", "shell",
        "petrobras", "vale", "bradesco", "itaú", "santander", "netflix",
        "hbo", "prime", "youtube", "telegram", "whatsapp", "safari",
        "chrome", "firefox", "opera", "skype", "zoom", "adobe",
        "spotify", "deezer", "pinterest", "uber", "ifood", "rappi",
        "airbnb", "booking", "trivago", "shopee", "mercadolivre", "magalu"
    ],
    "feelings": [
        "alegria", "tristeza", "amor", "raiva", "felicidade", "medo",
        "saudade", "ansiedade", "esperança", "gratidão", "empolgação",
        "frustração", "euforia", "angústia", "carinho", "confiança",
        "entusiasmo", "orgulho", "compaixão", "surpresa", "nostalgia",
        "contentamento", "admiração", "preocupação", "decepção", "ciúme",
        "ternura", "desespero", "serenidade", "otimismo", "solidão",
        "coragem", "insegurança", "arrependimento", "vergonha", "alívio",
        "fascinação", "indignação", "melancolia", "satisfação", "tédio",
        "espanto", "desânimo", "respeito", "afeto", "curiosidade",
        "determinação", "realização", "encantamento", "prazer", "paz",
        "calma", "tranquilidade","irritação", "inquietação", "dúvida",
        "desconforto", "empolgação", "exaustão", "esgotamento", "fúria",
        "nervosismo", "paixão", "pânico", "prazer", "preguiça",
        "rancor", "remorso", "repulsa", "simpatia", "medo", "tensão",
        "timidez", "tormento", "tristeza", "bravura", "vingança",
        "vivacidade", "vontade", "zelo", "abandono", "adoração",
        "amizade", "antipatia", "apego", "nojo", "bondade", "bravura",
        "carência", "companheirismo", "culpa", "dedicação", "desprezo",
        "dignidade", "diversão", "dor", "empatia", "entrega", "estresse",
        "euforia", "felicidade", "fervor", "fidelidade", "frieza", "fúria",
        "gentileza", "hostilidade", "humildade", "inveja", "lealdade"
    ]
}


